### ISSUE TITLE
Wrong snapshot version resolution in 1.9.1

### ISSUE THREAD

**Issue by lwasylkowski** [allegro/axion-release-plugin#238]
Seems like my PR broke snapshot version resolution:

```groovy
def "should return snapshot version of the more recent version when final and snapshot tags on the same commit in the past"() {
    given:
    repository.tag('release-1.0.0')
    repository.tag('release-1.1.0-alpha')
    repository.commit(['*'], 'some commit')
    repository.commit(['*'], 'some merge from another branch...')

    VersionProperties versionProps = versionProperties().build()

    when:
    VersionContext version = resolver.resolveVersion(versionProps, tagRules, nextVersionRules)

    then:
    version.previousVersion.toString() == '1.0.0'
    version.version.toString() == '1.1.0'
    version.snapshot
}
```

This test will fail on current master. Seems like resolver now always resolves to the stable version, thus with commits after the release the version will only ever increase by patch version. This change seems to fix things:

```diff
--- a/src/main/groovy/pl/allegro/tech/build/axion/release/domain/VersionResolver.groovy
+++ b/src/main/groovy/pl/allegro/tech/build/axion/release/domain/VersionResolver.groovy
@@ -135,8 +135,8 @@ class VersionResolver {
 
         def versionList = versions.asList()
         Collections.sort(versionList, Collections.reverseOrder())
-        
-        Version version = versionList.find { !isVersionNextVersion[it] } ?: versionList[0] ?: versionFactory.initialVersion()
+
+        Version version = versionList.find { !isVersionNextVersion[it] || !versionToCommit[it].isHead } ?: versionList[0] ?: versionFactory.initialVersion()
```

What would happen after this change is that release tag has a precedence only if it's on HEAD, otherwise we will use essentially what's the old resolution, which was broken in that one case but not the others.

I'm deeply sorry for introducing the bug. If time permits I'll try to see if there's an elegant way of writing easily readable version resolver test that covers (and with that specifies) all important combinations of final releases/alpha releases/commits.

I'm opening a pull request that fixes this particular bug in the meantime

**Comment by adamdubiel** [comment]
No worries. I thought that tests cover all major cases and happy-paths. Turns out they don't. I will review & release new version in the evening.

**Comment by adamdubiel** [comment]
Oh and if there is need for introducing more tests, i will take care of it not to delay the release.

**Comment by lwasylkowski** [comment]
Take your time -- if someone wasn't affected by the first bug they can continue to use 1.9.0, and I've released private 1.9.2 with this fixed for our purposes in the meantime (and maybe we'll catch something else with that, too)

**Comment by cliffred** [comment]
The snapshot version resolution is still broken after this fix (#239) when using -Prelease.useHighestVersion

The test below fails because it prints 'Project version: 1.0.1-SNAPSHOT' instead of 2.0.0-SNAPSHOT

```groovy
def "should return alpha tag if useHighestVersion is set to true"() {
        given:
        buildFile('')

        runGradle('release', '-Prelease.version=1.0.0', '-Prelease.localOnly', '-Prelease.disableChecks')
        repository.commit(['*'], "commit after release-1.0.0")
        runGradle('markNextVersion', '-Prelease.version=2.0.0', '-Prelease.localOnly', '-Prelease.disableChecks')

        when:
        def result = runGradle('currentVersion', '-Prelease.useHighestVersion')

        then:
        result.output.contains('2.0.0')
        result.task(":currentVersion").outcome == TaskOutcome.SUCCESS
    }
```

**Comment by adamdubiel** [comment]
I created new PR to fix (hopefully) all problems with version sorting: #246 .

To isolate the problems, i created new class: `VersionSorter`. Class comments contain the precedence used. Please also take a look at `VersionSorterTest` which tests cases that i came up with. All tests (including the once @cliffred posted) pass on this branch.

**Comment by adamdubiel** [comment]
Done, 1.9.2 is out :)

**Comment by baptistemesta** [comment]
👍 many thanks :)
